services:
  backend:
    build: Data-Analysis-Project-02/product/backend/
    container_name: backend_fast_api
    ports:
      - "8000:8000"
    command: uvicorn backend:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - me-cfs-depression-classifier

  frontend:
    build: Data-Analysis-Project-02/product/frontend/
    container_name: frontend_streamlit
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - me-cfs-depression-classifier
    environment:
      BACKEND_URL: http://backend:8000/

networks:
  me-cfs-depression-classifier:
    driver: bridge



